Apps/Mascota/urls.py
from django.conf.urls import url, include
from Apps.Mascota.views import add_mas, list_mas, upd_mas, del_mas, list_adop_mas, adop_mas

app_name = "Mascota"

urlpatterns = [
    url(r'^Formulario_mascota$', add_mas, name='Formulario_mascota'),
    url(r'^Listado_mascota$', list_mas, name='Listado_mascota'), 
    url(r'^Modificar_mascota/(?P<id_mascota>\d+)/$', upd_mas, name='Modificar_mascota'),
    url(r'^Eliminar_mascota/(?P<id_mascota>\d+)/$', del_mas, name='Eliminar_mascota'),
    url(r'^Listado_adopcion_mascota$', list_adop_mas, name='Listado_adopcion_mascota'),
]

Apps/Menu/urls.py
from django.conf.urls import url, include
from .import views

app_name = "Menu"

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

Apps/Usuario/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'Usuario'

urlpatterns = [
    url(r'^Formulario_usuario/$', views.add_user, name='Formulario_usuario'),
]

Proyecto_Mis_Perris/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import static
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from rest_framework import routers
from Apps.Usuario import views

from . import settings


router = routers.DefaultRouter()
router.register(r'user', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)


urlpatterns = [ 
    url(r'^admin/', admin.site.urls),
    url(r'', include('Apps.Menu.urls')),
    path('usuario', include(('Apps.Usuario.urls', 'usuario'), namespace='usuario')),
    path('accounts/', include('allauth.urls')),
    url(r'^mascota/', include ('Apps.Mascota.urls')),
    url(r'^usuario/', include ('Apps.Usuario.urls')),
    path('login/', LoginView.as_view(), name="Login"),
    path('logout/', LogoutView.as_view(), name="Logout"),
    path('misperrisApi/', include(router.urls)),
    path('', include('pwa.urls')), 
]

#nombre del admin
admin.site.site_header = "Administracion Mis Perris"
admin.site.index_title = "Mis Perris"
admin.site.site_title = "Administracion Mis Perris"

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Apps/Mascota/models.py
from django.db import models
from Apps.Usuario.models import Usuario
# Create your models here.

class Mascota(models.Model):
    nombre = models.CharField(max_length = 50)
    raza = models.CharField(max_length = 50)
    foto = models.ImageField(upload_to='img_reg_mas')
    descripcion = models.CharField(max_length = 100)
    estado_perro = (
        ('Disponible', 'Disponible'),
        ('Rescatado', 'Rescatado'),
        ('Adoptado', 'Adoptado')
    )
    estado = models.CharField(max_length = 20, choices = estado_perro)
    usuario = models.ForeignKey(Usuario, null = True, blank = True, on_delete = models.CASCADE)

    def __str__(self):
        return self.nombre
    

Apps/Menu/models.py
from django.db import models

# Create your models here.

Apps/Usuario/models.py
from django.db import models
from django.dispatch import receiver
from allauth.account.signals import user_signed_up

# Create your models here.
#Usuario
class Usuario(models.Model):
    rut = models.CharField(primary_key = True, max_length = 15)
    nombre = models.CharField(max_length = 40)
    telefono = models.CharField(max_length = 40)
    correo = models.EmailField()
    nacimiento = models.DateField()
    region = models.CharField(max_length = 30)
    comuna = models.CharField(max_length = 30)
    vivienda = models.CharField(max_length = 30)

    def Guardar(self):
        self.save()

    def __str__(self):
        return self.nombre


def create_user_profile(request, user, **kwargs):
    profile = Profile.objects.create(user=user)
    profile.save()

Apps/Mascota/forms.py
from django import forms
from .models import Mascota

class Mascota_form(forms.ModelForm):
    class Meta:
        model = Mascota
        fields = ['nombre', 'raza', 'foto', 'descripcion', 'estado',]
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'input-100'}),
            'raza': forms.TextInput(attrs={'class':'input-50'}),
            'foto': forms.FileInput(attrs={'class':'input-50'}),
            'descripcion': forms.TextInput(attrs={'class':'input-100'}),
            'estado': forms.Select(attrs={'class':'input-50'}),
        }

Apps/Usuario/forms.py
from django import forms
from .models import Usuario

class Usuario_form(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('rut', 'nombre', 'telefono', 'correo', 'nacimiento', 'region', 'comuna', 'vivienda',)

Apps/Mascota/views.py
from django.shortcuts import render, redirect
#Importamos el formulario generado en forms.py
from .forms import Mascota_form
from .models import Mascota
#Importamos las apps
from Apps import Menu, Usuario
# Create your views here.

#llamamos el HTML de agregar mascotas
def index_add_mascota(request):
    return render(request, 'index_add_mas.html', {})

#Funcion que al ser un metodo post , se guarda la información ingresada en el formulario
def add_mas(request):
    if request.method == 'POST':
        form = Mascota_form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('Menu:index',)
    else:
        form = Mascota_form()
        return render(request, 'index_add_mas.html', {'form':form})

#Funcion que me lista todas las mascotas ordenadas por nombre
def list_mas(request):
    mascota = Mascota.objects.all().order_by('nombre')
    return render(request, 'index_list_mas.html', {'perros':mascota})

#Funcion que edita los campos de las mascotas
def upd_mas(request, id_mascota):
    mascota = Mascota.objects.get(id = id_mascota)
    if request.method == 'GET':
        form = Mascota_form(instance = mascota)
    else:
        form = Mascota_form(request.POST, request.FILES, instance = mascota)
        if form.is_valid():
            mascota = form.save()
            mascota.save()
            return redirect('Mascota:Listado_mascota')
    return render(request, 'index_upd_mas.html', {'form':form})

#Funcion que elimina las mascotas
def del_mas(request, id_mascota):
    mascota = Mascota.objects.get(id = id_mascota)
    perro = Mascota.objects.all().order_by('nombre')
    if request.method == 'POST':
        mascota.delete()
        return redirect('Mascota:Listado_mascota')
    return render(request, 'index_del_mas.html', {'mascota':mascota})


def list_adop_mas(request):
    mascota = Mascota.objects.filter(estado = 'Disponible').order_by('nombre')
    return render(request, 'index_list_adop_mas.html', {'perros':mascota})

def adop_mas(request, id_mascota):
    mascota = Mascota.objects.get(id = id_mascota)
    mascota.estado = 'Adoptado'
    mascota.save()
    return redirect('Mascota:Listado_adopcion_mascota')

Apps/Menu/views.py
from django.shortcuts import render
# Create your views here.

def index(request):
    return render(request, 'index.html')

Apps/Usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from Apps.Usuario.serializers import UserSerializers, GroupSerializers


from .forms import Usuario_form
from .models import Usuario
from Apps import Menu, Mascota
 

# Create your views here.

#Vistas login y logout
def index_add_usuario(request):
    return render(request, 'index_add_us.html', {})

def index_login_user(request):
    return render(request, 'index_login_us.html', {})

def index_logout_user(request):
    return render(request, 'index_login_us.html', {})

#
def add_user(request):
    if request.method == 'POST':
        form = Usuario_form(request.POST)
        if form.is_valid():
            username = form.cleaned_data['nombre']
            password = form.cleaned_data['telefono']
            email = form.cleaned_data['correo']
            usuario = User.objects.create_user(username=username, email=email, password=password)
            form.save()
            usuario.save()
            return redirect('Menu:index',)
    else:
        form = Usuario_form()
        return render(request, 'index_add_us.html', {'form':form})

#Vista para los serializers
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializers


class GroupViewSet(viewsets.ModelViewSet):
    queryset = Group.objects.all()
    serializer_class = GroupSerializers

Apps/Mascota/templates/index_add_mas.html
{% extends 'index.html' %}

{% block title %} Registro Máscota {% endblock %}

{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="es">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <script src="{% static 'js/add_mas.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/style_add_mas.css' %}">
    </head>

    <body background="{% static 'img/Fot.jpg' %}">
        <h1>Formulario Registro</h1>
        <form class="form_reg" method="POST" action="" enctype="multipart/form-data" > {% csrf_token %}
            <h2 class="title">Registra una mascota</h2>
                <div class="contenedor">
                    <input class="input-100" name="nombre" type="text" placeholder="Nombre mascota..." pattern="[A-za-Z]" onkeypress="return validatexto(event)" required autofocus>
                    <input class="input-50" name="raza" type="text" placeholder="Raza predominante..." pattern="[A-za-Z]" onkeypress="return validatexto(event)" required>
                    <input class="input-50" name="foto" type="file" placeholder="Foto"  required>
                    <input class="input-100" name="descripcion" type="text" placeholder="Descripción" required>
                    {{form.estado}}
                    <input class="btn_reg" type="submit" value="Registrar">
                </div>
        </form>
    </body>

</html>

{% endblock %}

{% block footerbase %}

{% endblock %}

Apps/Mascota/templates/index_del_mas.html
{% extends 'index.html' %}

{% block title %} Eliminar Máscota {% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style_del_mas.css' %}">
    <body background={% static 'img/feliz.jpg' %}>
        <form method="POST">
            {% csrf_token %}
            <h1>¿Está seguro(a) que desea eliminar a {{mascota.nombre}}?</h1>
            <div class="botones">
                <button class="btn btn-eliminar" type="submit">Sí, eliminar</button>
                <a class="btn btn-default" href="{% url 'Mascota:Listado_mascota' %}">Cancelar</a>
            </div>
        </form>
    </body>
{% endblock %}

{% block footerbase %}
{% endblock %}

Apps/Mascota/templates/index_list_adop_mas.html
{% extends 'index.html' %}

{% block title %} Adopta una mascota {% endblock %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'css/style_list_mas.css' %}">
    </head>

    <body background={% static 'img/Feliz.jpg' %}>
        <h1>Lista de perros</h1>
        <div class="tabla-content">
            <table class="tabla">
                <tr>
                    <th>Nombre</th>
                    <th>Raza Predominante</th>
                    <th>Foto</th>
                    <th>Descripción</th>
                    <th>Estado</th>
                    <th>Adoptar</th>
                </tr>
                {% if perros %}
                {% for alguno in perros %}
                <tr>
                    <td>{{alguno.nombre}}</td>
                    <td>{{alguno.raza}}</td>
                    <td><img src="{{alguno.foto.url}}" width="60" height="60"></img></td>
                    <td>{{alguno.descripcion}}</td>
                    <td>{{alguno.estado}}</td>
                    <td><a class="btn btn-modificar" href="{% url 'Mascota:Adoptar_mascota' alguno.id %}">Adoptar</a></td>
                </tr>
                {% endfor %}
                {% else %}
                    <h1>No hay mascotas disponibles para adoptar</h1>
                {% endif %}
            </table>    
        </div>
    </body>

</html>

{% endblock %}

{% block footerbase %}

{% endblock %}

Apps/Mascota/templates/index_list_mas.html
{% extends 'index.html' %}

{% block title %} Listado Mascotas {% endblock %}

{% block content %}
{% load static%}
<!DOCTYPE html>
<html lang="es">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'css/style_list_mas.css' %}">
    </head>

    <body background="{% static 'img/Feliz.jpg' %}">
        <h1>Lista de perros</h1>
        <div class="tabla-content">
            <table class="tabla">
                <tr>
                    <th>#</th>
                    <th>Nombre</th>
                    <th>Raza Predominante</th>
                    <th>Foto</th>
                    <th>Descripción</th>
                    <th>Estado</th>
                    <th>Modificar</th>
                    <th>Eliminar</th>
                </tr>
                {% if perros %}
                    {% for alguno in perros%}
                    <tr>
                        <td>{{alguno.id}}</td>
                        <td>{{alguno.nombre}}</td>
                        <td>{{alguno.raza}}</td>
                        <td><img src="{{alguno.foto.url}}" width="60" height="60"></img></td>
                        <td>{{alguno.descripcion}}</td>
                        <td>{{alguno.estado}}</td>
                        <td><a class="btn btn-modificar" href="{% url 'Mascota:Modificar_mascota' alguno.id %}">Modificar</a></td>
                        <td><a class="btn btn-eliminar" href="{% url 'Mascota:Eliminar_mascota' alguno.id %}" >Eliminar</a></td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <h1>No hay registro de mascotas</h1>
                {% endif %}
            </table>    
        </div>
    </body>

</html>
{% endblock %}

{% block footerbase %}

{% endblock %}

Apps/Mascota/templates/index_upd_mas.html
{% extends 'index.html' %}

{% block title %} Modificar Mascotas {% endblock %}

{% block content %}
{% load static%}
<!DOCTYPE html>
<html lang="es">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'css/style_upd_mas.css' %}">
    </head>

    <body background = {% static 'img/Fot.jpg' %}>
        <h1>Modifica la mascota</h1>
            <form class="form_reg" method="POST" action="" enctype="multipart/form-data" > {% csrf_token %}
              <h2 class="title">Modificar mascota</h2>
                <div class="contenedor">
                    {{form.nombre}}
                    {{form.raza}}
                    {{form.foto}}
                    {{form.descripcion}}
                    {{form.estado}}
                    <input class="btn_reg" type="submit" value="Registrar">
                </div>
            </form>
    </body>

</html>
{% endblock %}

{% block footerbase %}
{% endblock %}

Apps/Menu/templates/index.html
{% load static %}
{% load pwa %}
<!DOCTYPE html>
<html lang="es">

    <head>
        {% progressive_web_app_meta %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="{% static 'js/slide.js' %}"></script>
        <title>{% block title%} Mis Perris {% endblock %}</title>
    </head>

    <body onload="showSlides(1)">
        {% block navegador %}
        <div class="barra">
            <header class="img_logo"> 
                <div>
                   <a href="{% url 'Menu:index' %}"><img id="logo" src="{% static 'img/logo.png' %}"> </a>
                </div>
            </header>
            <nav>
                {% if user.username %} 


                    {% if user.is_superuser%}
                        
                        <a href="{% url 'Menu:index' %}">Inicio</a>
                        <a href="{% url 'Usuario:Formulario_usuario' %}">Registro Usuario</a>
                        <a href="{% url 'Mascota:Formulario_mascota' %}">Agregar mascota</a>
                        <a href="{% url 'Mascota:Listado_mascota' %}">Listar mascota</a>
                        <a href="/misperrisApi">API</a>

                    {% else %}
                    
                    <a href="{% url 'Menu:index' %}">Inicio</a>
                    <a href="{% url 'Menu:index' %}">Servicios</a>
                    <a href="{% url 'Menu:index' %}">¿Quiénes somos?</a>
                    <a href="{% url 'Mascota:Listado_adopcion_mascota' %}">Adopta</a>

                    {% endif %}
                    
                    <a href="{% url 'Logout' %}">Salir</a>
                {% else %}
                    
                    <button onclick="Drop()" class="btn_log dropbtn">Log In</button>
                    <div id="mydropdown" class="dropdown-content">
                        <a href="{% url 'Login' %}">Ingresar</a>
                        <a href="{% url 'Usuario:Formulario_usuario' %}">Registro</a>
                    </div>
                    <a href="{% url 'Menu:index' %}">Inicio</a>
                    <a href="{% url 'Menu:index' %}">Servicios</a>
                    <a href="{% url 'Menu:index' %}">¿Quiénes somos?</a>
                    <a href="{% url 'Menu:index' %}">Contáctanos</a>
                    
                {% endif %}
            </nav>
        </div>
        {% endblock %}

        {% block content %}
        <div class="contenedor-slider">
            <div class="slide fade">
                <div class="imagen1">
                    <img class="adop" src="{% static 'img/slide/Apolo.jpg' %}">
                </div>
                <div class="text">Desde que él llegó a nuestras vidas todo ha sido mejor</div>
            </div>
            <div class="slide fade">
                <div class="imagen2">
                    <img class="adop" src="{% static 'img/slide/Duque.jpg' %}" alt="">
                </div>
                <div class="text">Ahora no me siento solo gracias a mi perrito</div>
            </div>
            <div class="slide fade">
                <div class="imagen3">
                    <img class="adop" src="{% static 'img/slide/Tom.jpg' %}" alt="">
                </div>
                <div class="text">Nos encantó Nuestro perro</div>
            </div>

            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
        </div>  
        <section>
            <div id="inf_contacto">
                <div class="celular">
                    <p>+56 9 9876 5431</p>
                </div>
                <div class="descripcion">
                    <p>Rescate y adopción de perros callejeros</p>
                </div>
                <div class="redes">
                    <img id="icface" src="{% static 'img/icons/facebook.png' %}"></img>
                    <img id="icgoogle" src="{% static 'img/icons/google.png' %}"></img>
                    <img id="icinsta" src="{% static 'img/icons/instagram.png' %}"></img>
                    <img id="icgmail" src="{% static 'img/icons/correo.png' %}"></img>
                </div>
            </div>
        </section>

        <section class="articulos">
            <article class="articulo1">
                <h1>RESCATE</h1>
                <h2>ETAPA 1</h2>
                <hr>
                <p>Rescatamos perros en situación de peligro. Los rehabilitamos y los preparamos para buscarles un hogar</p>
                <img src="{% static 'img/articulos/perritoart1.png' %}">
            </article>

            <article class="articulo2">
                <img src="{% static 'img/articulos/perritoart2.png' %}">
                <h1>CROWFUNDIG</h1>
                <h2>FINANCIAMIENTO</h2>
                <hr>
                <p>Sigue nuestras redes sociales para informarte acerca de las diversas campañas y actividades que realizamos para obtener financimiento para seguir ayudando</p>
            </article>
        </section>

        <div class="galeria">
            <div class="container">
                <img src="{% static 'img/rescatados/Bigotes.jpg' %}" class="image">
                <div class="overlay">
                    <div class="text2">
                        Me llamo Bigotes y me encanta jugar
                    </div>
                </div>
            </div>
            <div class="container">
                <img src="{% static 'img/rescatados/Wifi.jpg' %}" class="image">
                <div class="overlay">
                    <div class="text2">
                        Me dicen wifi y soy tímido
                    </div>
                </div>
            </div>
            <div class="container">
                <img src="{% static 'img/rescatados/Chocolate.jpg' %}" class="image">
                <div class="overlay">
                    <div class="text2">
                    Soy Chocolate y tengo una linda mirada
                    </div>
                </div>
            </div>
            <div class="container">
                <img src="{% static 'img/rescatados/Luna.jpg' %}" class="image">
                <div class="overlay">
                    <div class="text2">
                        Hola, me llamo Luna y soy recién nacida
                    </div>
                </div>
            </div>
            <div class="container">
                <img src="{% static 'img/rescatados/Pexel.jpg' %}" class="image">
                <div class="overlay">
                    <div class="text2">
                    Mi dueño me llama Pexel y soy feliz            
                    </div>
                </div>
            </div>
            <div class="container">
                <img src="{% static 'img/rescatados/Maya.jpg' %}" class="image">
                <div class="overlay">
                    <div class="text2">
                        Soy Maya y soy pequeñita
                    </div>
                </div>
            </div>
            <div class="container">
                <img src="{% static 'img/rescatados/Oso.jpg' %}" class="image">
                <divo class="overlay">
                    <div class="text2">
                        Soy juguetón con los niños y me apodan Oso
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}

        {% block footerbase %}
        <footer class="footerbase">
            <p>Desarrollo Web y Mobile</p>
        </footer>
        {% endblock %}
    </body>
</html>

Apps/Usuario/templates/index_add_us.html
{% extends 'index.html' %}

{% block title %} Contáctanos {% endblock %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="es">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'css/style_add_us.css' %}">
        <script src="{% static 'js/add_us.js' %}"></script>
        <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
        <script src="{% static 'js/jquery.validate.js' %}"></script>
        <script src="{% static 'js/Form.js' %}"></script>
    </head>

    <body background="{% static 'img/corriendo.jpg' %}">
        <h1>Formulario de Registro</h1>
        <form id="mi-formulario" class="form_reg" action="" method="POST" > {% csrf_token %}
            <h2 class="title">Crea tu cuenta</h2>
            <div class="contenedor">
                <input class="input-100" type="text" name="rut" placeholder="Rut..." oninput="checkRut(this)" required autofocus>
                <input class="input-100" type="text" name="nombre" placeholder="Nombre completo..." pattern="[A-za-Z]" onkeypress="return validatexto(event)" required>
                <input id="telefono" class="input-50" type="password" name="telefono" placeholder="Ingrese Contraseña..." required>
                <input id="pass2" class="input-50" type="password" name="pass2" placeholder="Confirme Contraseña..." required>
                <input class="input-50" type="email" name="correo" placeholder="Correo electrónico..." pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" required>
                <input class="input-50" type="date" name="nacimiento" max="2001-01-01" placeholder="Fecha nacimiento" required> 
                <select class="input-50" name="region" required>
                    <option value="I de Tarapacá">I de Tarapacá</option>
                    <option value="II de Antofagasta">II de Antofagasta</option>
                    <option value="III de Atacama">III de Atacama</option>
                    <option value="IV de Coquimbo">IV de Coquimbo</option>
                    <option value="V de Valparaíso">V de Valparaíso</option>
                    <option value="VI del Libertador General Bernardo O'Higgins">VI del Libertador General Bernardo O'Higgins</option>
                    <option value="VII del Maule">VII del Maule</option>
                    <option value="VIII del Bío Bío">VIII del Bío Bío</option>
                    <option value="IX de la Araucanía">IX de la Araucanía</option>
                    <option value="X de los Lagos">X de los Lagos</option>
                    <option value="XI Aisén del General Carlos Ibáñez del Campo">XI Aisén del General Carlos Ibáñez del Campo</option>
                    <option value="XII de Magallanes y Antártica Chilena">XII de Magallanes y Antártica Chilena</option>
                    <option value="XIV de los Ríos">XIV de los Ríos</option>
                    <option value="XV de Arica y Parinacota">XV de Arica y Parinacota</option>
                </select>
                <select class="input-50" name="comuna" required>
                    <option value="Santiago">Santiago</option>
                    <option value="Concepción">Concepción</option>
                    <option value="Viña del mar">Viña del Mar</option>
                </select>
                <select class="input-50" name="vivienda" required>
                    <option value="cas_cpg">Casa con patio grande</option>
                    <option value="cas_cpp">Casa con patio pequeño</option>
                    <option value="cas_sp">Casa sin patio</option>
                    <option value="dep">Departamento</option>
            </select>
                <button class="btn_reg" type="submit"> Registrar </button>
            </div>
        </form> 
        <script>
            $(document).ready(function(){
                $("button").click(function(){
                    $("#mi-formulario").validate();
                })
            })
        </script>
    </body>
    
</html>
{% endblock %}

{% block footerbase %}

{% endblock %}